### ISSUE TITLE
Add "attendee" as an option on the visa letter form

### ISSUE THREAD

**Issue by drewbrew** [djangocon/2022.djangocon.us#118]
**Expected behavior:**
General attendees who need a visa letter who aren't speakers or opportunity grant recipients should be able to indicate as such

**Actual behavior:**
The form doesn't make it clear that the user can submit the form without selecting either option.

![image](https://user-images.githubusercontent.com/7773256/182688006-2ab82c7e-9e4c-4a0a-947a-6f08754209fd.png)

Perhaps we should rename "Select Option" to "neither" or something like that?

**Comment by noahalorwu** [comment]
@drewbrew  let's rename **Select Option** to  "Neither"

**Comment by drewbrew** [comment]
Works for me!
