### ISSUE TITLE
Update Sponsors Info

### ISSUE THREAD

**Issue by adamfast** [djangocon/2022.djangocon.us#15]
_site/sponsors/information/index.html needs to be updated - it refers to incorrect sponsor packages, references 500 people in September, etc.

Needs to mention the hybrid component of the event for 2022, and not sure how we want to address audience - we almost certainly won't have 500 attendees in person in COVID world.

Page also says sponsorship is closed

**Comment by williln** [comment]
@adamfast Do we have updated sponsor levels?
