### ISSUE TITLE
Update Organizers Info 

### ISSUE THREAD

**Issue by williln** [djangocon/2022.djangocon.us#18]
All organizers need: 

- A headshot 
- A title (default: "Organizer") 
- Optional links: Twitter, GitHub, personal website 

Also need to remove folks who aren't organizing this year. 

- [x] Adam Fast 
- [x] Drew Winstel
- [x] Catherine Holmes -- Update title to Sponsors & Tickets Chair 
- [x] Dawn Wages
- [x] Jorge Gimeno-- Update title to Onsite Coordinator 
- [x] Lacey Williams Henschel -- Update photo, update title to Communications and Website 
- [ ] Noah Alorwu -- All info. Title: Onsite Coordinator 
- [x] Kojo Idrissa -- Update title to Orientation, Lightning Talks & Sprints 
- [x] Logan Kilpatrick-- All info. Title: Communications & Website 
- [x] Jeff Triplett
- [x] Katia Lira
- [x] David Fischer -- Update title to Onsite Coordinator 
- [ ] Sergey Lyapustin -- All info. Title: Organizer  
- [x] Carol Ganz
- [x] Jen Myers
- [x] Josue Balandrano Coronel 
- [x] Kati Michel 

To remove: 
- [x] Vishbajit Pathak

**Comment by williln** [comment]
@logankilpatrick Can you make a PR with the following? 

- A jpg in `/static/img/organizers` with your photo, cropped to be square
- A new `.md` file in `_organizers/` -- just copy and paste one of the other ones and update with your info https://github.com/djangocon/2022.djangocon.us/tree/main/_organizers Make sure the path to your photo includes the filename you chose. 

Thanks! 


@drewbrew @jefftriplett Looks like Noah and Sergey aren't in the org yet so I can't tag them.

**Comment by jefftriplett** [comment]
@KatherineMichel @xirdneh I didn't see you both on the sheet either, but I assumed you were around or helping ad-hoc because of DEFNA. Just double-checking.

**Comment by xirdneh** [comment]
@jefftriplett that's correct. I totally forgot to go over that file. Thanks 🙂

**Comment by williln** [comment]
@jefftriplett @xirdneh @KatherineMichel Sorry about that! I'll update the PR and add y'all back -- I was just going off the organizers spreadsheet.

**Comment by KatherineMichel** [comment]
I think I should be on there. I oversaw the website design along with Jeff (we cancelled the conference, then didn't have it in San Diego). I will also help out ad hoc. I was swamped at the time that the organizer sheet was circulating (might have had Covid at the time).

**Comment by logankilpatrick** [comment]
@KatherineMichel agreed! Feel free to make a PR with the info, I think this was just closed as housekeeping.

**Comment by williln** [comment]
@KatherineMichel You were added back a while back! https://2022.djangocon.us/organizers/ But yes if 
there are other active organizers who are not on the website, they should feel free to submit a PR!
